CREATE TABLE IF NOT EXISTS Users_FULLSTACK (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Musics_FULLSTACK (
    id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    file VARCHAR(255) NOT NULL,
    album VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users_FULLSTACK(id)
);


CREATE TABLE IF NOT EXISTS Genre_FULLSTACK (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Music_Genre_FULLSTACK (
    music_id VARCHAR(255) NOT NULL,
    genre_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (music_id) REFERENCES Musics_FULLSTACK(id),
    FOREIGN KEY (genre_id) REFERENCES Genre_FULLSTACK(id)
);